# Generated by Django 4.1 on 2022-08-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.jpeg", max_length=300, upload_to="avatars/"
            ),
        ),
    ]
