# Generated by Django 4.1 on 2022-08-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="PostComment",
        ),
        migrations.RenameModel(
            old_name="Tag",
            new_name="PostTag",
        ),
    ]
